In [6]:
import random

a = random.randrange(1, 10)
print(a)

5


In [10]:
import random

a = random.normalvariate(0, 1)
print(a)

0.07578606539447273


In [20]:
import random

mylist = list("ABCDEFG")
a = random.sample(mylist, 3)
random.shuffle(mylist)
print(mylist)
print(a)

['A', 'F', 'E', 'D', 'G', 'C', 'B']
['G', 'C', 'D']


In [24]:
import random

random.seed(1)
print(random.random())
print(random.randint(1,10))
random.seed(2)
print(random.random())
print(random.randint(1,10))

0.13436424411240122
2
0.9560342718892494
1


In [28]:
import secrets

a = secrets.randbelow(10)
print(a)

9


In [40]:
import secrets

a = secrets.randbits(4)
#1111
print(a)

13


In [42]:
import secrets

mylist = list("ABCDEFGH")
a = secrets.choice(mylist)
print(a)

F


In [44]:
import numpy as np

a = np.random.rand(3,3)
print(a)

[[0.48721659 0.35161581 0.41076951]
 [0.77070257 0.70887436 0.69765024]
 [0.21515531 0.70115819 0.00334043]]


In [48]:
import numpy as np

a = np.random.randint(0, 10, (3,4))
print(a)

[[3 0 1 8]
 [2 2 9 7]
 [9 8 1 0]]


In [52]:
import numpy as np

arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr)
np.random.shuffle(arr)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5 6]
 [1 2 3]
 [7 8 9]]


In [54]:
import numpy as np

np.random.seed(1)
print(np.random.rand(3,3))
np.random.seed(1)
print(np.random.rand(3,3))

[[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]
 [1.86260211e-01 3.45560727e-01 3.96767474e-01]]
[[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]
 [1.86260211e-01 3.45560727e-01 3.96767474e-01]]
